Models/Forum.cs
using System;
using System.Collections.Generic;
using System.Text;
using LambdaForums.Models.Forums;
namespace LambdaForums.Models
{
    public class Forum
    {
        public int Id{get;set;}
        public string Title{get;set;}
        public string Description{get;set;}
        public DateTime Created{get;set;}
        public string ImageUrl{get;set;}

        public virtual IEnumerable<Post> Posts{get;set;}
    }
}

Models/Forums/ForumIndexModel.cs
using System;
using System.Collections.Generic;
using System.Text;
using LambdaForums.Models;

namespace LambdaForums.Models.Forums
{
    public class ForumIndexModel
    {
        public IEnumerable<ForumListingModel> ForumList{get;set;}
    }
}

Models/Forums/ForumListingModel.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace LambdaForums.Models.Forums
{
    public class ForumListingModel
    {
        public int Id{get;set;}
        public string Name{get;set;}
        public string Description {get;set;}
        public string ImageUrl{get;set;}
    }
}

Models/Forums/ForumTopicModel.cs
using System;
using System.Collections.Generic;
using System.Text;
using LambdaForums.Models;
using LambdaForums.Models.Posts;

namespace LambdaForums.Models.Forums
{
    public class ForumTopicModel
    {
        public ForumListingModel Forum{get;set;}
        public IEnumerable<PostListingModel> Posts {get;set;}
    }
}

Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LambdaForums.Models.Posts;
using LambdaForums.Services;
using LambdaForums.Models;
using LambdaForums.Models.Forums;

namespace LambdaForums.Controllers
{
    public class ForumController:Controller
    {
        private readonly IForumServices _forumServices;
        private readonly IPost _postServices;
        public ForumController(IForumServices forumServices,IPost postServices)
        {
            _forumServices=forumServices;
            _postServices=postServices;
        }
        public IActionResult Index()
        {
            var forums=_forumServices.GetAll()
                        .Select(forum=>new ForumListingModel{
                        Id=forum.Id,
                        Name=forum.Title,
                        Description=forum.Description});

            var model=new ForumIndexModel
            {
                ForumList= forums
            };

                return View(model);
        }

        public IActionResult Topic(int Id)
        {
            var forum = _forumServices.GetById(Id);
            var posts = forum.Posts;
            var postListings = posts.Select(post => new PostListingModel
            {
                Id=post.Id,
                AuthorId=post.User.Id,
                AuthorRating=post.User.Rating,
                Title=post.Title,
                DatePosted=post.Created.ToString(),
                RepliesCount=post.Replies.Count(),
                Forum=BuildForumListing(post)

            });
            var model=new ForumTopicModel
            {
                Posts=postListings,
                Forum=BuildForumListing(forum)
            };
            return View(model);
        }
        private ForumListingModel BuildForumListing(Post post)
        {
            var forum=post.Forum;
           return BuildForumListing(forum);
        }
        private ForumListingModel BuildForumListing(Forum forum)
        {
            
            return new ForumListingModel
            {
                Id=forum.Id,
                Name=forum.Title,
                Description=forum.Description,
                ImageUrl=forum.ImageUrl

            };
        }
    
    }
}

Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LambdaForums.Models.Posts;
using LambdaForums.Services;
using LambdaForums.Models;
using LambdaForums.Models.Forums;

namespace LambdaForums.Controllers
{
    public class PostController:Controller
    {
        private readonly IPost _postService;
        public PostController(IPost postService)
        {
            _postService=postService;
        }
        public IActionResult Index(int id)
        {
            var post=_postService.GetById(id);
            var replies=BuildPostReplies(post.Replies);
            var model=new PostIndexModel
            {   
                Id=post.Id,
                Title=post.Title,
                AuthorId=post.User.Id,
                AuthorName=post.User.UserName,
                AuthorImageUrl=post.User.ProfileImageUrl,
                AuthorRating=post.User.Rating,
                Created=post.Created,
                PostContent=post.Content,
                Replies=replies
            };
            return View(model);
        }
        private IEnumerable<PostReplyModel> BuildPostReplies(IEnumerable<PostReply> replies)
        {
            return replies.Select(reply=>new PostReplyModel
            {
                Id=reply.Id,
                AuthorName=reply.User.UserName,
                AuthorId=reply.User.Id,
                AuthorImageUrl=reply.User.ProfileImageUrl,
                AuthorRating=reply.User.Rating,
                Created=reply.Created,
                ReplyContent=reply.Content

            });
        }
    }
}

Views/Forum/Index.cshtml
@model  LambdaForums.Models.Forums.ForumIndexModel

<h1>Forums</h1>

<table class="table table-hover" id="forumIndexTable">
    <tbody>
        @foreach (var forum in Model.ForumList)
        {
            <tr>
                <td>
                    <a asp-action="Topic" asp-controller="Forum" asp-route-id="@forum.Id">
                    @forum.Name
                    </a>
                </td>
                <td>
                    @forum.Description
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Forum/Topic.cshtml
@model LambdaForums.Models.Forums.ForumTopicModel

<h1>Welcome to @Model.Forum.Name Forum!</h1>

@if(Model.Posts.Any())
{
    <table class="table table-bordered table-hover"> 
        <tbody>
            @foreach (var post in Model.Posts)
            {
                <tr>
                    <td>
                        <a asp-controller="Post" asp-action="Index" asp-route-id="@post.Id">
                           @post.Title  
                        </a>
                        
                        
                    </td>
                    <td>
                        @post.AuthorName
                    </td>
                    <td>
                        @post.DatePosted
                    </td>
                    <td>
                        @post.RepliesCount
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
   <div class="noPost">
       <h3>
           it looks like there are no @Model.Forum.Name posts yet.<br/>
           Why not 
           <a asp-controller="Post" asp-action="Create" asp-route-id="@Model.Forum.Id">
               <span>create</span>
           </a>
       </h3>

   </div> 
}